# ───────────────────────────
# Project basics
# ───────────────────────────
site_name: Cinemate Docs
site_description: Documentation for Cinemate 
site_url: https://tiramisioux.github.io/cinemate/
repo_url: https://github.com/tiramisioux/cinemate
edit_uri: blob/cinemate-v3.1/docs/
repo_name: GitHub
dev_addr: 0.0.0.0:8000            # live-preview reachable from your laptop

# ───────────────────────────
# Navigation (edit to match your .md files)
# ───────────────────────────
nav:
  - Home: index.md
  - Getting started: getting-started.md

  - Manual installation: installation-steps.md

  - Configuration:
      - Connecting to the camera via SSH: ssh.md
      - Settings file: settings-json.md
      - Using the CLI: cli-user-guide.md
      - Commands reference: cli-commands.md

  - Operating the camera:
      - Web GUI: web-gui.md
      - HDMI GUI: simple-gui.md
      - Sensors: sensors.md
      - Audio recording: audio-recording.md
      - Digital zoom: digital-zoom.md
      - Speed ramping & shutter angle synchronization: speed-ramping.md
      - Dual sensors: dual-sensors.md

  - System management:
      - System services: system-services.md
      - Modifying config.txt: config-txt.md
      - Recompiling cinepi-raw: compiling-cinepi-raw.md
      - Hotspot: hotspot-logic.md
      - Overclocking the Pi: overclocking.md
      - Backing up the SD card: backing-up-sd-card.md

  - Redis:
      - Basic API: redis-guide.md
      - Key reference: redis-keys.md

  - Hardware:
      - Preinstalled hardware: hardware-overview.md

  - Builds:
      - Bare bones: bare-bones-build.md
      - Brick: brick.md 

  - Troubleshoooting:
      - Known issues: known-issues.md
      - Troubleshooting: troubleshooting.md
  
  - Contributing:
      - Todo: todo.md
      - Contributing guide: contributing.md

  - Download PDF: renders/Cinemate-Docs.pdf

# ───────────────────────────
# Theme
# ───────────────────────────
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    logo: material/library
  
  font:
    text: Roboto
    code: Roboto Mono

  language: en
  
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - toc.integrate 
    - toc.follow
    - content.code.copy
    - content.action.edit       # “Edit this page” link to repo
    
  palette:
    - scheme: default           # WCAG-AA compliant base
      primary: black
      accent: black

extra_css:  
  - overrides/github-markdown.css
  #- docs/stylesheets/pdf.css  
# ───────────────────────────
# Markdown add-ons
# ───────────────────────────
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: "#"            # tiny link-icon on headings
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji

# ───────────────────────────
# Plugins
# ───────────────────────────
plugins:
  - search
plugins: # PDF build (runs only when ENABLE_PDF_EXPORT=1 is set in CI)
  - with-pdf:
      # ── meta ─────────────────────────────

      # ── cover & back cover ───────────────
      cover: true
      back_cover: true
      cover_title: "Cinemate"
      cover_subtitle: "User & Builder Guide"
      cover_logo: docs/assets/images/CINEMATE.jpg   # relative to docs/

      # ── build behaviour ─────────────────
      output_path: renders/Cinemate-Docs.pdf  # already using this
      #custom_template_path: stylesheets         # new – where styles.scss lives
      
      # ── layout ─────────────────
      two_columns_level: 2        # experimental two-column layout
      toc_level: 3                # depth of autogenerated TOC

      verbose: true