# ───────────────────────────
# Project basics
# ───────────────────────────
site_name: Cinemate Docs
site_description: Documentation for Cinemate 
site_url: https://tiramisioux.github.io/cinemate/
repo_url: https://github.com/tiramisioux/cinemate
edit_uri: blob/cinemate-v3.1/docs/
repo_name: GitHub
dev_addr: 0.0.0.0:8000            # live-preview reachable from your laptop 

# ───────────────────────────
# Navigation (edit to match your .md files)
# ───────────────────────────
nav:
  - Home: index.md
  - Introduction: readme.md
  - Quick start:
      - Getting started with a minimal build: getting-started.md
  - Customising your build:
    - Connecting via SSH: ssh.md
    - Settings file: settings-json.md
    - Adding hardware controls: hardware-controls.md
    - Configuring the Wi-Fi hotspot: hotspot-logic.md
  - Using the camera:
      - CinePi RAW terminal commands: cli-user-guide.md
      - HDMI GUI: simple-gui.md
      - Web GUI: web-gui.md
      - Sensors: sensors.md
      - Audio recording: audio-recording.md
      - Digital zoom: digital-zoom.md
      - Speed ramping & shutter angle synchronization: speed-ramping.md
      - Dual sensors: dual-sensors.md
      - Cinemate terminal commands: cli-commands.md
  - System management:
      - System services: system-services.md
      - Modifying config.txt: config-txt.md
      - Recompiling cinepi-raw: compiling-cinepi-raw.md
      - Overclocking the Pi: overclocking.md
      - Backing up the SD card: backing-up-sd-card.md
  - Reference & troubleshooting:
      - Redis API: redis-guide.md
      - Key reference: redis-keys.md
      - Hardware overview: preinstalled-hardware.md
      - Known issues: known-issues.md
      - Troubleshooting: troubleshooting.md
  - Cinemate builds:
      - Bare bones build: bare-bones-build.md
      - Box build: brick.md
  - Development & contributing:
      - Manual installation (from scratch): installation-steps.md
      - Todo: todo.md
      - Contributors: contributors.md
      - Contributing to the project: contributing.md
      - Acknowledgements: acknowledgments.md
  #- Download PDF: renders/Cinemate-Docs.pdf
# Theme
# ───────────────────────────
theme:
  name: readthedocs
  custom_dir: docs/overrides
  icon:
    logo: material/library
  
  font:
    text: Roboto
    code: Roboto Mono

  language: en
  
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - toc.integrate 
    - toc.follow
    - content.code.copy
    - content.code.select

    # Read the Docs specific
    - collapse_navigation: True,
    - sticky_navigation: True,
    - navigation_depth: 4,
    - includehidden: True,
    - titles_only: False
      
  palette:
    - scheme: default           # WCAG-AA compliant base

extra_css:
  # - overrides/github-markdown.css
  - templates/styles.scss
  - stylesheets/extra.css
extra_javascript:
  - js/ko-fi-widget.js
  - js/init-mermaid.js
# ───────────────────────────
# Markdown add-ons
# ───────────────────────────

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - codehilite
  - toc:
      permalink: "#"            # tiny link-icon on headings
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

# ───────────────────────────
# Plugins
# ───────────────────────────
plugins:
  - search
  - mermaid2:                        # list item ➜ 2-space indent
      javascript: "https://cdn.jsdelivr.net/npm/mermaid@10.4.0/dist/mermaid.min.js"
  # - with-pdf:
  #     # ── template ─────────────────────────────
  #     custom_template_path: docs/stylesheets     # where styles.scss now lives

  #     # ── cover & back cover ───────────────
  #     cover: true
  #     back_cover: true
  #     cover_title: "Cinemate"
  #     cover_subtitle: "User & Builder Guide"
  #     cover_logo: docs/assets/images/CINEMATE.jpg   # relative to docs/

  #     # ── build behaviour ─────────────────
  #     output_path: renders/Cinemate-Docs.pdf  # already using this
      
  #     # ── layout ─────────────────
  #     two_columns_level: 2        # experimental two-column layout
  #     toc_level: 3                # depth of autogenerated TOC

  #     verbose: true