# ───────────────────────────
# Project basics
# ───────────────────────────
site_name: Cinemate Docs
site_description: Documentation for Cinemate 
site_url: https://tiramisioux.github.io/cinemate/
repo_url: https://github.com/tiramisioux/cinemate
edit_uri: blob/cinemate-v3.1/docs/
repo_name: GitHub
dev_addr: 0.0.0.0:8000            # live-preview reachable from your laptop

# ───────────────────────────
# Navigation (edit to match your .md files)
# ───────────────────────────
nav:
  - Home: index.md
  - Getting started:
      - Overview: overview.md
      - Installation: install-guide.md
      - Settings file: settings-json.md
      - Cinemate CLI: cli-commands.md
  - Code:
      - modules:
        - cinepi_multi.py: cinepi-multi.md
        - cinepi_controller.py: controller-methods.md
  - Redis:
      - Basic API: redis-guide.md
      - Key reference: redis-keys.md
    

# ───────────────────────────
# Theme
# ───────────────────────────
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    logo: material/library
  
  font:
    text: Roboto
    code: Roboto Mono

  language: en
  
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - toc.follow
    - content.code.copy
    - content.action.edit       # “Edit this page” link to repo
  palette:
    - scheme: default           # WCAG-AA compliant base
      primary: black
      accent: black

extra_css:
  - https://cdn.jsdelivr.net/npm/github-markdown-css@5/github-markdown.css

# ───────────────────────────
# Markdown add-ons
# ───────────────────────────
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: "#"            # tiny link-icon on headings
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji

# ───────────────────────────
# Plugins
# ───────────────────────────
plugins:
  - search
  - pdf-export:                 # one click PDF at /pdf/Cinemate-Docs.pdf
      combined: true
      verbose: false
      media_type: print
  - git-revision-date-localized:  # shows “Last updated” in footer
      fallback_to_build_date: true
