#!/usr/bin/env bash
# Build a CineMate release image from the running Pi.
#
# The manual procedure in docs/backing-up-sd-card.md images the card exactly as
# it is. That is right for a backup and wrong for a release: the card carries
# whatever sensor, hotspot and GPIO configuration the operator has been
# shooting with, and everyone who flashes the release then inherits it.
#
# So this script brackets the documented dd/pishrink/xz with a swap of the two
# files that hold that configuration:
#
#   settings.jsonc  ->  the copy tracked at the checked-out commit, comments
#                       and all. Restored with `git checkout --`, never
#                       reserialized -- those comments are part of the product
#                       (see the handbook's conventions/style.md).
#   config.txt      ->  the stock managed block, generated by
#                       cinemate-install.sh's own configure_boot_config().
#                       Not a copy of it: this script sources the installer and
#                       calls the real function, so there is one definition of
#                       "stock config.txt" and it cannot drift from what a
#                       clean install actually writes.
#
# Afterwards both files go back exactly as they were.
#
# Restoring is the part that has to be reliable, so it is defended three ways:
# an EXIT/INT/TERM trap covers a failed or interrupted run, the operator's
# files are stashed on the destination volume (which survives a reboot) rather
# than in RAM, and a leftover stash is detected and replayed at the start of
# the next run. A hard power cut mid-run therefore leaves the Pi on stock
# config, not with the operator's setup lost.
#
# Nothing here reboots, and nothing here touches which branch either repository
# is on -- do that yourself before running this. config.txt only takes effect
# at boot and the image is read off the block device, so the swap is visible to
# dd immediately while the running camera is left alone.
#
# Usage:
#   sudo ~/cinemate/scripts/make-release-image.sh [--dry-run] [--restore-only]
#
# --help lists every option. docs/backing-up-sd-card.md documents the plain
# backup procedure this is built on; it deliberately says nothing about this
# script, which is a maintainer tool rather than something users run.

set -Eeuo pipefail

RI_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RI_REPO_DIR="$(cd "$RI_SCRIPT_DIR/.." && pwd)"

# ── Options ──────────────────────────────────────────────────────────────────
PI_USER="${PI_USER:-pi}"
PI_HOME="${PI_HOME:-/home/$PI_USER}"
CINEMATE_DIR="${CINEMATE_DIR:-$PI_HOME/cinemate}"
CINEPI_RAW_DIR="${CINEPI_RAW_DIR:-$PI_HOME/cinepi-raw}"
IMAGE_DEST_DIR="${IMAGE_DEST_DIR:-/media/RAW}"
# BOOT_CONFIG and PISHRINK are overridable only so
# _test/test_release_image_dry_run.py can point the whole run at a scratch tree
# and prove the files come back byte for byte, and that a full imaging pass
# deletes the uncompressed image. A real run never sets either.
BOOT_CONFIG="${BOOT_CONFIG:-/boot/firmware/config.txt}"
PISHRINK="${PISHRINK:-/usr/local/bin/pishrink.sh}"
IMAGE_DEVICE="${IMAGE_DEVICE:-}"          # empty => detect the disk holding /
STOP_CINEMATE="${STOP_CINEMATE:-0}"       # 1 => stop cinemate-autostart while imaging
ALLOW_STASH_ON_IMAGED_DISK="${ALLOW_STASH_ON_IMAGED_DISK:-0}"

DRY_RUN=0
RESTORE_ONLY=0

# ── Output ───────────────────────────────────────────────────────────────────
ri_log()    { printf '[release-image] %s\n' "$*"; }
ri_detail() { printf '[release-image]      %s\n' "$*"; }
ri_warn()   { printf '[release-image] WARNING: %s\n' "$*" >&2; }
ri_die()    { printf '[release-image] ERROR: %s\n' "$*" >&2; exit 1; }

# Progress. A release image is an hour of near-silence otherwise: dd and xz
# each run for many minutes with nothing but their own output, and over SSH it
# is genuinely hard to tell a slow step from a hung one. Every phase announces
# itself as [n/total] with the elapsed clock, and reports how long it took when
# it ends, so the previous run's numbers tell you what to expect from this one.
RI_STEP_N=0
RI_STEP_TOTAL=6
RI_T0=$SECONDS
RI_STEP_T=$SECONDS

ri_hms() { printf '%d:%02d:%02d' $(($1 / 3600)) $((($1 % 3600) / 60)) $(($1 % 60)); }

ri_step_done() {
    if (( RI_STEP_N == 0 )); then return 0; fi
    printf '[release-image]      ... done in %s\n' "$(ri_hms $((SECONDS - RI_STEP_T)))"
}

ri_step() {
    ri_step_done
    RI_STEP_N=$((RI_STEP_N + 1))
    RI_STEP_T=$SECONDS
    printf '\n[release-image] [%d/%d] %s   (elapsed %s)\n' \
        "$RI_STEP_N" "$RI_STEP_TOTAL" "$*" "$(ri_hms $((SECONDS - RI_T0)))"
}

usage() {
    cat <<'EOF'
Usage: sudo ~/cinemate/scripts/make-release-image.sh [--dry-run] [--restore-only]

Swaps settings.jsonc and /boot/firmware/config.txt to their stock values, makes
the image the way docs/backing-up-sd-card.md describes, then puts both files
back. Does not change which branch either repository is on.

Options:
  --dry-run        Do the whole swap and restore, but print the dd/pishrink
                   commands instead of running them. Verifies the bracket in
                   seconds instead of an hour.
  --restore-only   Replay a stash left behind by an interrupted run, then exit.
  -h, --help       This text.

Environment:
  IMAGE_DEST_DIR              Where the image is written. Default: /media/RAW
  IMAGE_DEVICE                Disk to image. Default: the disk holding /
  STOP_CINEMATE=1             Stop cinemate-autostart while imaging
  SENSOR_MODEL, CAM_PORT      Passed through to the installer's config.txt
                              generator. Default: imx477 on cam0, which is what
                              a clean install writes.
  CINEMATE_DIR, CINEPI_RAW_DIR, PI_USER
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run)      DRY_RUN=1 ;;
        --restore-only) RESTORE_ONLY=1 ;;
        -h|--help)      usage; exit 0 ;;
        *)              usage >&2; ri_die "Unknown argument: $1" ;;
    esac
    shift
done

# ── The stock config.txt comes from the installer, not from here ─────────────
# cinemate-install.sh is guarded so sourcing it defines its functions without
# running an install. configure_boot_config() is then the single source of
# truth for the managed block; CONFIG_TXT_PATH is how it is aimed elsewhere.
RI_INSTALLER="$RI_REPO_DIR/cinemate-install.sh"
[[ -f "$RI_INSTALLER" ]] || ri_die "Missing $RI_INSTALLER"
# shellcheck source=/dev/null
source "$RI_INSTALLER"

# Sourcing the installer installs two traps of its own: an ERR trap that
# reports with its prefix, and an EXIT trap for its build-zram cleanup (a no-op
# here, since nothing armed it). Take both back before anything else runs --
# the EXIT trap in particular is the one this script needs for restoring.
trap 'printf "[release-image] ERROR: line %s while running: %s\n" "$LINENO" "$BASH_COMMAND" >&2' ERR
trap - EXIT

# Own truthiness test rather than the installer's is_true(): that one uses
# ${1,,}, which is bash 4+, and keeping this script's own code free of the
# installer's helpers is what lets the dry-run test exercise it anywhere.
ri_is_true() {
    case "$1" in
        1|true|TRUE|True|yes|YES|Yes|on|ON|On) return 0 ;;
        *) return 1 ;;
    esac
}

# Quiet variant of the installer's run_as_pi(): that one logs to stdout, which
# corrupts every $(...) that wants a value back.
ri_as_pi() { sudo -u "$PI_USER" -- "$@"; }

ri_rev() { ri_as_pi git -C "$1" rev-parse HEAD 2>/dev/null || printf 'unknown'; }

# Owner and mode of a file. GNU stat first (the Pi), BSD second so the test
# suite can exercise this code on a Mac rather than stubbing past it, and a
# caller-supplied default last -- failing to read a mode is not a reason to
# abandon a release.
ri_owner() {
    stat -c '%U:%G' "$1" 2>/dev/null \
        || stat -f '%Su:%Sg' "$1" 2>/dev/null \
        || printf '%s' "$2"
}
ri_mode() {
    stat -c '%a' "$1" 2>/dev/null \
        || stat -f '%Lp' "$1" 2>/dev/null \
        || printf '%s' "$2"
}

# ── Stash ────────────────────────────────────────────────────────────────────
RI_STASH_DIR="$IMAGE_DEST_DIR/.cinemate-release-image"
RI_STATE="$RI_STASH_DIR/state.env"
RI_RESTORED=0

ri_restore() {
    # Idempotent, and safe to call when there is nothing to restore.
    [[ -f "$RI_STATE" ]] || return 0
    if (( RI_RESTORED )); then return 0; fi
    RI_RESTORED=1

    ri_step "Restoring your configuration"

    local RI_CINEMATE_WAS_ACTIVE=0
    local RI_SETTINGS_OWNER="$PI_USER:$PI_GROUP" RI_SETTINGS_MODE=644
    local RI_CONFIG_OWNER="root:root" RI_CONFIG_MODE=644
    # shellcheck source=/dev/null
    source "$RI_STATE"

    # Both files go back byte for byte. settings.jsonc in particular is never
    # reserialized -- json.dumps() would silently delete all ~70 of its
    # comments, a bug this project has already shipped once.
    # Each restore is independently guarded: a failure here must report and
    # let the next one run, never abort the function under `set -e` and leave
    # one file swapped back and the other still on stock.
    local ri_failed=0

    if [[ -f "$RI_STASH_DIR/settings.jsonc" ]]; then
        ri_detail "settings.jsonc -> $CINEMATE_DIR/settings.jsonc"
        install -o "${RI_SETTINGS_OWNER%%:*}" -g "${RI_SETTINGS_OWNER##*:}" \
            -m "$RI_SETTINGS_MODE" \
            "$RI_STASH_DIR/settings.jsonc" "$CINEMATE_DIR/settings.jsonc" || {
            ri_warn "Could not restore settings.jsonc -- your copy is still at $RI_STASH_DIR/settings.jsonc"
            ri_failed=1
        }
    fi

    if [[ -f "$RI_STASH_DIR/config.txt" ]]; then
        ri_detail "config.txt -> $BOOT_CONFIG"
        install -o "${RI_CONFIG_OWNER%%:*}" -g "${RI_CONFIG_OWNER##*:}" \
            -m "$RI_CONFIG_MODE" "$RI_STASH_DIR/config.txt" "$BOOT_CONFIG" || {
            ri_warn "Could not restore config.txt -- your copy is still at $RI_STASH_DIR/config.txt"
            ri_failed=1
        }
    fi

    if ri_is_true "$RI_CINEMATE_WAS_ACTIVE"; then
        ri_detail "Starting cinemate-autostart again"
        systemctl start cinemate-autostart || ri_warn "cinemate-autostart did not start"
    fi

    if (( ri_failed )); then
        ri_step_done
        ri_warn "Restore incomplete. $RI_STASH_DIR is being kept -- your files are in it."
        return 0
    fi

    rm -rf "$RI_STASH_DIR"
    ri_step_done
    ri_log "Restore complete -- the Pi is back on your configuration (total $(ri_hms $((SECONDS - RI_T0))))"
}

# ── Restore-only ─────────────────────────────────────────────────────────────
if (( RESTORE_ONLY )); then
    [[ "$(id -u)" -eq 0 ]] || ri_die "Run with sudo"
    [[ -f "$RI_STATE" ]] || ri_die "No stash at $RI_STASH_DIR -- nothing to restore"
    RI_STEP_TOTAL=1
    ri_restore
    exit 0
fi

# ── Preflight ────────────────────────────────────────────────────────────────
[[ "$(id -u)" -eq 0 ]] || ri_die "Run with sudo -- this writes /boot/firmware and reads the boot device"

if (( DRY_RUN )); then RI_STEP_TOTAL=4; fi
ri_step "Preflight"

id "$PI_USER" >/dev/null 2>&1 || ri_die "User $PI_USER does not exist"
[[ -f "$CINEMATE_DIR/settings.jsonc" ]] || ri_die "Missing $CINEMATE_DIR/settings.jsonc"
[[ -d "$CINEMATE_DIR/.git" ]] || ri_die "$CINEMATE_DIR is not a git repository -- stock settings.jsonc comes from git"
[[ -d "$IMAGE_DEST_DIR" ]] || ri_die "$IMAGE_DEST_DIR is not mounted -- the image has nowhere to go"
mountpoint -q "$IMAGE_DEST_DIR" || ri_warn "$IMAGE_DEST_DIR is a plain directory, not a mount point"

if (( ! DRY_RUN )); then
    [[ -x "$PISHRINK" ]] || ri_die "Missing $PISHRINK on this Pi"
fi

# The disk to image: whatever backs /, unless told otherwise.
if [[ -z "$IMAGE_DEVICE" ]]; then
    ri_root_src="$(findmnt -no SOURCE / || true)"
    [[ -n "$ri_root_src" ]] || ri_die "Could not determine the device backing /"
    ri_root_disk="$(lsblk -no pkname "$ri_root_src" | head -n1 || true)"
    [[ -n "$ri_root_disk" ]] || ri_die "Could not determine the whole disk behind $ri_root_src"
    IMAGE_DEVICE="/dev/$ri_root_disk"
fi
[[ -b "$IMAGE_DEVICE" ]] || ri_die "$IMAGE_DEVICE is not a block device"

# The config.txt this script rewrites must actually be on the disk being
# imaged, or the swap would not land in the image at all.
ri_boot_src="$(findmnt -no SOURCE --target "$(dirname "$BOOT_CONFIG")" || true)"
[[ -n "$ri_boot_src" ]] || ri_die "$(dirname "$BOOT_CONFIG") is not mounted"
ri_boot_disk="/dev/$(lsblk -no pkname "$ri_boot_src" | head -n1)"
[[ "$ri_boot_disk" == "$IMAGE_DEVICE" ]] || \
    ri_die "$BOOT_CONFIG lives on $ri_boot_disk but the image would be taken from $IMAGE_DEVICE"

# The stash holds the operator's real settings.jsonc, hotspot password and all.
# On the imaged disk it would ship inside the release.
ri_dest_src="$(findmnt -no SOURCE --target "$IMAGE_DEST_DIR" || true)"
ri_dest_disk="/dev/$(lsblk -no pkname "$ri_dest_src" 2>/dev/null | head -n1 || true)"
if [[ "$ri_dest_disk" == "$IMAGE_DEVICE" ]]; then
    if ri_is_true "$ALLOW_STASH_ON_IMAGED_DISK"; then
        ri_warn "$IMAGE_DEST_DIR is on the disk being imaged; your settings.jsonc will ship inside the release"
    else
        ri_die "$IMAGE_DEST_DIR is on $IMAGE_DEVICE, the disk being imaged. Point IMAGE_DEST_DIR at another volume (set ALLOW_STASH_ON_IMAGED_DISK=1 to override)"
    fi
fi

ri_device_bytes="$(blockdev --getsize64 "$IMAGE_DEVICE")"
ri_avail_bytes="$(df --output=avail -B1 "$IMAGE_DEST_DIR" | tail -n1 | tr -d ' ')"
ri_detail "Imaging $IMAGE_DEVICE ($(numfmt --to=iec "$ri_device_bytes")) into $IMAGE_DEST_DIR ($(numfmt --to=iec "$ri_avail_bytes") free)"
if (( ri_avail_bytes < ri_device_bytes )); then
    ri_warn "Less free space than the device is large. dd writes sparsely so this often still fits, but a full card will fail mid-image."
fi

if [[ -f "$RI_STATE" ]]; then
    ri_warn "A stash from an earlier, interrupted run is present at $RI_STASH_DIR"
    ri_warn "Replaying it first so this run starts from your real configuration."
    ri_restore
    RI_RESTORED=0
fi

# ── Capture, then swap ───────────────────────────────────────────────────────
ri_step "Saving your configuration to $RI_STASH_DIR"
mkdir -p "$RI_STASH_DIR"
# The stash holds the operator's settings.jsonc, hotspot password included, so
# it wants to be private. On a filesystem with no permission bits (the exFAT
# case above) chmod cannot deliver that -- say so once and carry on rather than
# failing the release over the mode of a directory that is deleted at the end.
chmod 700 "$RI_STASH_DIR" 2>/dev/null || \
    ri_warn "$IMAGE_DEST_DIR has no permission bits, so $RI_STASH_DIR cannot be made private. It is removed when the run finishes."

RI_CINEMATE_WAS_ACTIVE=0
if ri_is_true "$STOP_CINEMATE" && systemctl is-active --quiet cinemate-autostart; then
    RI_CINEMATE_WAS_ACTIVE=1
fi

# Plain cp, not `cp -a`. The stash lives on the destination volume, and on the
# Pi that is an exFAT SSD with no concept of ownership -- `cp -a` there fails
# outright ("failed to preserve ownership", confirmed on hardware 2026-09-15),
# taking the whole run with it before a single byte was imaged.
#
# Preserving attributes on the stash copy was never the point anyway: what has
# to survive is the attributes of the ORIGINALS, so record those and reapply
# them on the way back. That also drops this script's previous assumption that
# config.txt is 644 root:root and settings.jsonc 644 pi:pi -- it now restores
# whatever was actually there.
# state.env is written FIRST, before either copy. It is the marker the next
# run looks for, so writing it last would make a crash mid-stash invisible --
# a stash directory holding the operator's files that nothing would ever
# replay. Restoring a file the state names but the stash does not hold is
# already a no-op, so the early write costs nothing.
{
    printf 'RI_CINEMATE_WAS_ACTIVE=%q\n' "$RI_CINEMATE_WAS_ACTIVE"
    printf 'RI_SETTINGS_OWNER=%q\n' "$(ri_owner "$CINEMATE_DIR/settings.jsonc" "$PI_USER:$PI_GROUP")"
    printf 'RI_SETTINGS_MODE=%q\n'  "$(ri_mode  "$CINEMATE_DIR/settings.jsonc" 644)"
    printf 'RI_CONFIG_OWNER=%q\n'   "$(ri_owner "$BOOT_CONFIG" "root:root")"
    printf 'RI_CONFIG_MODE=%q\n'    "$(ri_mode  "$BOOT_CONFIG" 644)"
} > "$RI_STATE"

cp "$CINEMATE_DIR/settings.jsonc" "$RI_STASH_DIR/settings.jsonc"
cp "$BOOT_CONFIG" "$RI_STASH_DIR/config.txt"

# Armed as soon as anything is stashed: from here every exit path restores.
# INT/TERM exit explicitly -- a bare handler would return and let the script
# carry on into dd as if nothing had happened.
trap ri_restore EXIT
trap 'ri_restore; exit 130' INT
trap 'ri_restore; exit 143' TERM

if (( RI_CINEMATE_WAS_ACTIVE )); then
    ri_log "Stopping cinemate-autostart for the duration of the image"
    systemctl stop cinemate-autostart
fi

ri_step "Swapping in the stock configuration"

# Stock settings.jsonc is simply the copy git already tracks at the commit that
# is checked out. Whatever branch you put the repo on is what ships.
if ri_as_pi git -C "$CINEMATE_DIR" diff --quiet -- settings.jsonc; then
    ri_detail "settings.jsonc already matches the tracked copy -- nothing to swap"
else
    ri_detail "settings.jsonc -> tracked copy at $(ri_as_pi git -C "$CINEMATE_DIR" rev-parse --short HEAD)"
    ri_as_pi git -C "$CINEMATE_DIR" checkout -- settings.jsonc
fi

# The installer's own generator, aimed at the real path. BACKUP_DIR is where
# its backup_file() drops the pre-swap copy -- a second safety net beside the
# stash. SENSOR_MODEL/CAM_PORT keep the installer's clean-install defaults
# (imx477 on cam0) unless the environment overrides them: that is what a
# release ships with.
ri_detail "config.txt -> stock block from cinemate-install.sh ($SENSOR_MODEL on $CAM_PORT)"

# configure_boot_config() calls the installer's backup_file(), which is another
# `cp -a` -- so BACKUP_DIR cannot live on the destination volume either, for
# the same exFAT reason as the stash. It goes to a scratch directory instead,
# removed immediately so it is not sitting on the card when dd reads it. The
# stash already holds a byte-for-byte copy of config.txt, so this backup is
# redundant; it exists only because the installer's function insists on one.
BACKUP_DIR="$(mktemp -d)"
CONFIG_TXT_PATH="$BOOT_CONFIG" configure_boot_config
rm -rf "$BACKUP_DIR"

# ── Image ────────────────────────────────────────────────────────────────────
RI_TS="$(date +%F_%H-%M-%S)"
# Lowercase throughout. The manual procedure in the docs images to Cinemate_*
# and renames on the way to cinemate_*, which only existed to tell the working
# file from the finished one; naming the raw image lowercase too means PiShrink
# already writes the final name and there is no rename step to get wrong.
RI_RAW="$IMAGE_DEST_DIR/cinemate_${RI_TS}.img"
RI_FINAL="${RI_RAW}.xz"
RI_MANIFEST="$IMAGE_DEST_DIR/cinemate_${RI_TS}.txt"

{
    printf 'CineMate release image\n'
    printf 'built          %s\n' "$RI_TS"
    printf 'image          %s\n' "$(basename "$RI_FINAL")"
    printf 'source device  %s (%s)\n' "$IMAGE_DEVICE" "$(numfmt --to=iec "$ri_device_bytes")"
    printf 'cinemate       %s\n' "$(ri_rev "$CINEMATE_DIR")"
    printf 'cinepi-raw     %s\n' "$(ri_rev "$CINEPI_RAW_DIR")"
    printf 'settings.jsonc tracked copy, unmodified\n'
    printf 'config.txt     stock block from cinemate-install.sh (SENSOR_MODEL=%s, CAM_PORT=%s)\n' "$SENSOR_MODEL" "$CAM_PORT"
} > "$RI_MANIFEST"

ri_detail "What this image will contain:"
sed 's/^/[release-image]      | /' "$RI_MANIFEST"

if (( DRY_RUN )); then
    ri_log "--dry-run: skipping the image itself. Would have run:"
    ri_detail "dd if=$IMAGE_DEVICE of=$RI_RAW bs=4M conv=noerror,sync,sparse status=progress"
    ri_detail "$PISHRINK -s -v -Z -a $RI_RAW"
    ri_detail "rm -f $RI_RAW   # the uncompressed image, once $RI_FINAL exists"
    rm -f "$RI_MANIFEST"
    exit 0
fi

# From here down this is docs/backing-up-sd-card.md verbatim, only with the
# device and paths resolved above instead of hardcoded.
ri_step "Imaging $IMAGE_DEVICE -> $(basename "$RI_RAW")"
ri_detail "dd reports bytes and rate below; expect roughly $(ri_hms $((ri_device_bytes / 40000000))) at 40 MB/s"
dd if="$IMAGE_DEVICE" of="$RI_RAW" bs=4M conv=noerror,sync,sparse status=progress

ri_step "Shrinking and compressing with PiShrink"
ri_detail "PiShrink shrinks the filesystem, then xz compresses it across all cores."
ri_detail "The xz pass is the slowest part and prints nothing until it finishes."
"$PISHRINK" -s -v -Z -a "$RI_RAW"

[[ -f "$RI_FINAL" ]] || ri_die "PiShrink did not produce $RI_FINAL"

# The uncompressed image is the size of the whole card. Nothing needs it once
# the .xz exists, and leaving it behind fills the volume for the next run.
ri_detail "Removing the uncompressed $(basename "$RI_RAW") ($(du -h "$RI_RAW" | cut -f1))"
rm -f "$RI_RAW"

ri_step_done
ri_log "Release image ready: $RI_FINAL ($(du -h "$RI_FINAL" | cut -f1))"
ri_log "Manifest: $RI_MANIFEST"

# Printed rather than assumed: the whole point is to paste it on the desktop
# computer without having to reconstruct the timestamped filename by hand.
ri_log "Copy it to your desktop computer with:"
printf '\n    scp %s@%s.local:%s ~/Downloads/\n\n' \
    "$PI_USER" "$(hostname -s 2>/dev/null || hostname)" "$RI_FINAL"

printf '__RELEASE_IMAGE__=%s\n' "$RI_FINAL"
printf '__RELEASE_MANIFEST__=%s\n' "$RI_MANIFEST"

# The EXIT trap restores both files from here.
