name: Deploy Vitepress to GitHub Pages

on:
  push:
    branches:
      - cinemate-v3 # Or your primary branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build Vitepress docs
        run: npm run docs:build

      - name: Deploy to GitHub Pages
        run: npm run docs:deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
