name: build-and-deploy-docs

on:
  push:
    branches: [main]        # rebuild on every push to main
    branches: [main, v3_dev]
  workflow_dispatch:        # manual “Run workflow” button

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install MkDocs toolchain
        run: |
          pip install mkdocs-material \
                      mkdocs-pdf-export-plugin \
                      mkdocs-git-revision-date-localized-plugin \
                      mkdocs-macros-plugin

      - name: Build site
        run: mkdocs build

      # Save the PDF as an artifact (optional but nice)
      - uses: actions/upload-artifact@v4
        with:
          name: cinemate-docs-pdf
          path: site/pdf/Cinemate-Docs.pdf

      # Publish HTML (and the PDF inside it) to the gh-pages branch
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site

