name: Generate Circuit Diagrams

on:
  push:
    paths:
      - "docs/schematics/wiring/*.fzz"
  workflow_dispatch:

jobs:
  generate-circuits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Fritzing CLI
        run: |
          sudo apt update
          sudo apt install -y fritzing fritzing-parts xvfb

      - name: Start Virtual Display (Xvfb)
        run: Xvfb :99 -screen 0 1024x768x16 &

      - name: Convert Fritzing Files to PNG
        run: |
          export DISPLAY=:99
          fritzing --export png docs/schematics/wiring/cinemate_circuit_simple.fzz --output docs/schematics/wiring/cinemate_circuit_simple.png
          fritzing --export png docs/schematics/wiring/cinemate_circuit_advanced.fzz --output docs/schematics/wiring/cinemate_circuit_advanced.png

      - name: Commit Generated PNGs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add docs/schematics/wiring/*.png
          git commit -m "Auto-generated circuit diagrams from Fritzing"
          git push
