name: Generate PDF

on:
  repository_dispatch:
    types: [generate_pdf]

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Clone main repo
        uses: actions/checkout@v3
        with:
          repository: Tiramisioux/cinemate
          token: ${{ secrets.MAIN_REPO_PAT }}
          path: source-repo

      - name: Generate PDF
        run: |
          mkdir -p pdf
          cd source-repo
          # Replace this with real logic
          echo "Generated PDF from latest docs" > ../pdf/output.pdf

      - name: Deploy to gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin gh-pages
          cp pdf/output.pdf .
          git add output.pdf
          git commit -m "Update PDF from docs update [skip ci]" || echo "No changes"
          git push origin gh-pages

