name: Generate Circuit Diagrams

on:
  push:
    paths:
      - "docs/schematics/wiring/*.py"
  workflow_dispatch:

jobs:
  generate-circuits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install xmltodict

      - name: Generate Fritzing Files
        run: |
          python3 docs/schematics/wiring/generate_fritzing.py

      - name: Install Fritzing CLI
        run: |
          sudo apt install -y fritzing fritzing-parts

      - name: Convert Fritzing Files to PNG
        run: |
          fritzing --export png docs/schematics/wiring/cinemate_circuit_simple.fzz --output docs/schematics/wiring/cinemate_circuit_simple.png
          fritzing --export png docs/schematics/wiring/cinemate_circuit_advanced.fzz --output docs/schematics/wiring/cinemate_circuit_advanced.png

      - name: Commit Generated Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add docs/schematics/wiring/*.fzz docs/schematics/wiring/*.png
          git commit -m "Auto-generated Fritzing files and circuit diagrams"
          git push
