name: Trigger PDF Generation

on:
  push:
    paths:
      - 'docs/**'      # only trigger on changes inside docs/
      - '.github/workflows/trigger-pdf.yml'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send dispatch to gh-pages
        run: |
          curl -X POST https://api.github.com/repos/tiramisioux/cinemate/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.DISPATCH_PAT }}" \
          -d '{"event_type": "generate_pdf"}'
